config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :receipes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :recipes
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
has_many :pictures
belongs_to :recipes
end

app/models/picture.rb
class Picture < ApplicationRecord
belongs_to :recipes
belongs_to :ingredients
end

app/models/receipe.rb
class Receipe < ApplicationRecord
has_many :ingredients
has_many :pictures
has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/receipes_controller.rb
class ReceipesController < ApplicationController
  before_action :set_receipe, only: %i[ show edit update destroy ]

  # GET /receipes or /receipes.json
  def index
    @receipes = Receipe.all
  end

  # GET /receipes/1 or /receipes/1.json
  def show
  end

  # GET /receipes/new
  def new
    @receipe = Receipe.new
  end

  # GET /receipes/1/edit
  def edit
  end

  # POST /receipes or /receipes.json
  def create
    @receipe = Receipe.new(receipe_params)

    respond_to do |format|
      if @receipe.save
        format.html { redirect_to @receipe, notice: "Receipe was successfully created." }
        format.json { render :show, status: :created, location: @receipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @receipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipes/1 or /receipes/1.json
  def update
    respond_to do |format|
      if @receipe.update(receipe_params)
        format.html { redirect_to @receipe, notice: "Receipe was successfully updated." }
        format.json { render :show, status: :ok, location: @receipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @receipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipes/1 or /receipes/1.json
  def destroy
    @receipe.destroy
    respond_to do |format|
      format.html { redirect_to receipes_url, notice: "Receipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipe
      @receipe = Receipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def receipe_params
      params.require(:receipe).permit(:name, :ingredient, :direction, :preparation_time, :cooking_time, :servings, :category, :picture, :created_by)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/receipes_helper.rb
module ReceipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/receipes/_form.html.erb
<%= form_with(model: receipe, local: true) do |form| %>
  <% if receipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receipe.errors.count, "error") %> prohibited this receipe from being saved:</h2>

      <ul>
      <% receipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :ingredient %>
    <%= form.text_area :ingredient %>
  </div>

  <div class="field">
    <%= form.label :direction %>
    <%= form.text_area :direction %>
  </div>

  <div class="field">
    <%= form.label :preparation_time %>
    <%= form.datetime_select :preparation_time %>
  </div>

  <div class="field">
    <%= form.label :cooking_time %>
    <%= form.datetime_select :cooking_time %>
  </div>

  <div class="field">
    <%= form.label :servings %>
    <%= form.text_field :servings %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture %>
  </div>

  <div class="field">
    <%= form.label :created_by %>
    <%= form.text_field :created_by %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/receipes/edit.html.erb
<h1>Editing Receipe</h1>

<%= render 'form', receipe: @receipe %>

<%= link_to 'Show', @receipe %> |
<%= link_to 'Back', receipes_path %>

app/views/receipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Receipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ingredient</th>
      <th>Direction</th>
      <th>Preparation time</th>
      <th>Cooking time</th>
      <th>Servings</th>
      <th>Category</th>
      <th>Picture</th>
      <th>Created by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receipes.each do |receipe| %>
      <tr>
        <td><%= receipe.name %></td>
        <td><%= receipe.ingredient %></td>
        <td><%= receipe.direction %></td>
        <td><%= receipe.preparation_time %></td>
        <td><%= receipe.cooking_time %></td>
        <td><%= receipe.servings %></td>
        <td><%= receipe.category %></td>
        <td><%= receipe.picture %></td>
        <td><%= receipe.created_by %></td>
        <td><%= link_to 'Show', receipe %></td>
        <td><%= link_to 'Edit', edit_receipe_path(receipe) %></td>
        <td><%= link_to 'Destroy', receipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receipe', new_receipe_path %>

app/views/receipes/new.html.erb
<h1>New Receipe</h1>

<%= render 'form', receipe: @receipe %>

<%= link_to 'Back', receipes_path %>

app/views/receipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @receipe.name %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @receipe.ingredient %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @receipe.direction %>
</p>

<p>
  <strong>Preparation time:</strong>
  <%= @receipe.preparation_time %>
</p>

<p>
  <strong>Cooking time:</strong>
  <%= @receipe.cooking_time %>
</p>

<p>
  <strong>Servings:</strong>
  <%= @receipe.servings %>
</p>

<p>
  <strong>Category:</strong>
  <%= @receipe.category %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @receipe.picture %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @receipe.created_by %>
</p>

<%= link_to 'Edit', edit_receipe_path(@receipe) %> |
<%= link_to 'Back', receipes_path %>